### ISSUE TITLE
may you share reference with algorithm description, to learn how it works?

### ISSUE THREAD

**Issue by Sandy4321** [vene/pyowl#2]
great code , thanks
only several questions
1
will it work on Windows?
2
will it work for python 3
3
may you share reference with algorithm description, to learn how it works?

thanks

**Comment by vene** [comment]
1. certainly, this is pure python, as long as you can install the dependencies it should work.
2. i believe yes
3. The reference is listed in the source code https://github.com/vene/pyowl/blob/master/pyowl.py#L21
